[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  NODE_VERSION = "22"

[context.deploy-preview]
  command = "npm run build"

[context.branch-deploy]
  command = "npm run build" 